services:
  - type: web
    name: telegram-webhook-bot
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: 7710160278:AAEuNEnQOfIz2zNMWGWLLNCiNwiBn_4h-gw