services:
  - type: web
    name: telegram-webhook-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7710160278:AAEuNEnQOfIz2zNMWGWLLNCiNwiBn_4h-gw
